# docker/docker-compose.yml

services:
  postgres:
    image: postgres:alpine
    container_name: synergo_postgres
    environment:
      POSTGRES_DB: synergo_db
      POSTGRES_USER: synergo_user
      POSTGRES_PASSWORD: synergo_2024!
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=fr_FR.UTF-8 --lc-ctype=fr_FR.UTF-8"
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
    networks:
      - synergo_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: synergo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - synergo_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: synergo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@synergo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8085:80"
    depends_on:
      - postgres
    networks:
      - synergo_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  synergo_network:
    driver: bridge
